[build]
  functions = "netlify/functions"  # Ruta donde están tus funciones de Netlify

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  headers = { 
    "Access-Control-Allow-Origin" = "*",           # Permitir cualquier origen
    "Access-Control-Allow-Methods" = "GET, POST, PUT, DELETE, OPTIONS",  # Métodos permitidos
    "Access-Control-Allow-Headers" = "Content-Type, Authorization"      # Encabezados permitidos
  }
